spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tfg}
    username: ${SPRING_DATASOURCE_USERNAME:tfg}
    password: ${SPRING_DATASOURCE_PASSWORD:tfg}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
